global:
  scrape_interval: 15s
  external_labels:
    monitor: 'localhost-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.88.0.102:9187']
